### ISSUE TITLE
Linux binary.

### ISSUE THREAD

**Issue by nodgear** [danielga/gm_stringtable#3]
Would you add a Linux compiled version to /releases ?

**Comment by danielga** [comment]
Can you try [these builds](https://github.com/danielga/gm_stringtable/releases/tag/1.1.3) please?

**Comment by nodgear** [comment]
Absolutely, i'm trying out today at night.

**Comment by nodgear** [comment]
I am deeply Sorry, i forgot about that and i am the one who requested binaries.
Worked Fine on my end using x86 version of srcds.

X64 version yet to test
