### ISSUE TITLE
Issue with altering "networkstrings" string table

### ISSUE THREAD

**Issue by VaasKahnGrim** [danielga/gm_stringtable#8]
So I can view data in it but every time I attempt to remove or change anything it causes a crash.

I'm trying to help a friend of mine to change a networkstrings ID at will. So far I managed to make a wrapper that can add a network string into the networkstrings string table. However I'm having a hard time with removing a network string from the string table or altering the index of a network string.

Right now this is usable for making netstrings but won't let me specify the exact id to give to a net string. Aswell over time making multiple new netstrings would result in unused network strings.

I was hoping you can give me some advice on how to go about deleting netstrings, changing the ID of a netstring or changing the netstring associated with an ID.

This is the wrapper so far

```
if SERVER then
	require("stringtable")

	--	Prints the string currently associated with an ID( WORKING )
	function net.PrintNetString(id)
		print(stringtable.Get(19):GetString(id))
	end

	--	Prints every Net String into console( WORKING )
	function net.PrintNetworkStrings()
		local netstrings = stringtable.Get( 19 ):GetTable()
		print( netstrings )
		PrintTable( netstrings )
	end

	--	Add a Network String into the string table( WORKING )
	function net.AddNetString( str )
		local newStringID
		local sTable = stringtable.Get( 19 )
			sTable:Lock( false )				--	not sure if this is really doing anything
			newStringID = sTable:AddString( true, str )		--	not sure why it wants a bool????
			sTable:Lock( true )

		return newStringID	--	Return the new string ID
	end

	--	Does Nothing, table shows up unaltered when calling net.PrintNetworkStrings() and the index is unchanged when calling net.PrintNetString()
	function net.SetNetString( id, str )
		local sTable = stringtable.Get( 19 )
			sTable:Lock( false )
			sTable:GetString( id, str )
			sTable:Lock( true )
	end

	function net.DeleteNetString( id )	--Crashes immediately
		local sTable = stringtable.Get( 19 )
			sTable:Lock( false )
			sTable:DeleteString( id )
			sTable:Lock( true )
	end
else
	function net.Incoming( len, ply )
		local ID = net.ReadHeader()
		print( "Recived Net Message ID: ", ID )

		if net.Receivers[ ID ] then
			return net.Receivers[ ID ]( len, ply )
		end
	end
end
```

**Comment by danielga** [comment]
Deleting strings or otherwise modifying them is dangerous, if you don't know how the engine is using them (like the models table). It is also implemented as a big hack. That said, what is stringtable 19? It is preferred to use `stringtable.Find` if you're looking for a specifically named stringtable. I can't tell you what `Lock` does, due to the non-existing documentation. For a clue as to what `AddString` parameters do, [look here](https://github.com/danielga/sourcesdk-minimal/blob/5806e89d8f067e9e871deb60c49a68af81e5a0fb/public/networkstringtabledefs.h).
